#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("RBAListDemo.Android.Resource", IsApplication=true)]

namespace RBAListDemo.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int sprite = 2130837505;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060015
			public const int addEntry = 2131099669;
			
			// aapt resource value: 0x7f060013
			public const int addList = 2131099667;
			
			// aapt resource value: 0x7f060006
			public const int btnAdd = 2131099654;
			
			// aapt resource value: 0x7f060009
			public const int btnAddImage = 2131099657;
			
			// aapt resource value: 0x7f060012
			public const int btnFacebook = 2131099666;
			
			// aapt resource value: 0x7f060010
			public const int imageView1 = 2131099664;
			
			// aapt resource value: 0x7f06000a
			public const int imgItem = 2131099658;
			
			// aapt resource value: 0x7f060008
			public const int imgProduct = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int linearLayout1 = 2131099655;
			
			// aapt resource value: 0x7f06000f
			public const int listItems = 2131099663;
			
			// aapt resource value: 0x7f060014
			public const int logout = 2131099668;
			
			// aapt resource value: 0x7f060011
			public const int progressBar1 = 2131099665;
			
			// aapt resource value: 0x7f060000
			public const int relativeLayout1 = 2131099648;
			
			// aapt resource value: 0x7f06000c
			public const int relativeLayout2 = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int relativeLayout3 = 2131099661;
			
			// aapt resource value: 0x7f060016
			public const int shareWishList = 2131099670;
			
			// aapt resource value: 0x7f060001
			public const int textView1 = 2131099649;
			
			// aapt resource value: 0x7f06000b
			public const int textView3 = 2131099659;
			
			// aapt resource value: 0x7f060004
			public const int txtAsking = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int txtDescription = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int txtName = 2131099650;
			
			// aapt resource value: 0x7f06000e
			public const int txtPrice = 2131099662;
			
			// aapt resource value: 0x7f060005
			public const int txtRetail = 2131099653;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ItemActivity = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ItemDetails = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ItemListItemView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ItemListView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int splashscreen = 2130903044;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int ListsView_Menu = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int ListView_Menu = 2131034113;
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
